<?php
$_SESSION["HWG_PROJECT_MODE"]='DEBUG'; // DEBUG / PROD
$_SESSION["HWG_USR_LANG"]='english';
if($_SESSION["HWG_PROJECT_MODE"]=='DEBUG'){
$_SESSION["HWG_PROJECT_VERSIONNUMBER"]='1.0';
$_SESSION["HWG_PROJECT_URL"]="http://".$_SERVER["HTTP_HOST"]."/assignlancer/website/";
} else {
$_SESSION["HWG_PROJECT_VERSIONNUMBER"]='1.0';
// $_SESSION["PROJECT_URL"]="http://.com/".$_SESSION["PROJECT_VERSION_NUMBER"]."/";
}
?>
<script type="text/javascript">
var PROJECT_URL = '<?php if(isset($_SESSION["HWG_PROJECT_URL"])) { echo $_SESSION["HWG_PROJECT_URL"]; } ?>';
var USR_LANG = '<?php if(isset($_SESSION["HWG_USR_LANG"])) { echo $_SESSION["HWG_USR_LANG"]; } ?>';
var SESSION_ID = '<?php echo session_id(); ?>';
var CLIENT_IPADDRESS = '<?php echo $_SERVER['REMOTE_ADDR']; ?>'; 
var QUEUE_ADDEDON = '<?php echo date('Y-m-d H:i:s'); ?>';
/* ALL ACCOUNTS */
var HWG_ACCOUNT_TYPE = '<?php if(isset($_SESSION["HWG_ACCOUNT_TYPE"])) { echo $_SESSION["HWG_ACCOUNT_TYPE"]; } ?>';
console.log("HWG_ACCOUNT_TYPE: "+HWG_ACCOUNT_TYPE); // CUSTOMER_LIVESUPPORT / CUSTOMERS / ADMINISTRATOR
/* ADMINISTRATOR ACCOUNT */
var ADMINISTRATOR_ACCOUNT_ID = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_ACCOUNTID"])){ echo $_SESSION["HWG_ADMINISTRATOR_ACCOUNTID"]; } ?>';
var ADMINISTRATOR_NAME = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_NAME"])){ echo $_SESSION["HWG_ADMINISTRATOR_NAME"]; } ?>';
var ADMINISTRATOR_EMAIL = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_EMAIL"])){ echo $_SESSION["HWG_ADMINISTRATOR_EMAIL"]; } ?>';
var ADMINISTRATOR_CREATEDON = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_CREATEDON"])){ echo $_SESSION["HWG_ADMINISTRATOR_CREATEDON"]; } ?>';
var ADMINISTRATOR_COUNTRY = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_COUNTRY"])){ echo $_SESSION["HWG_ADMINISTRATOR_COUNTRY"]; } ?>';
var ADMINISTRATOR_CURRENCY = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_CURRENCY"])){ echo $_SESSION["HWG_ADMINISTRATOR_CURRENCY"]; } ?>';
var ADMINISTRATOR_TIMEZONE = '<?php if(isset($_SESSION["HWG_ADMINISTRATOR_TIMEZONE"])){ echo $_SESSION["HWG_ADMINISTRATOR_TIMEZONE"]; } ?>';
console.log("ADMINISTRATOR_ACCOUNT_ID: "+ADMINISTRATOR_ACCOUNT_ID);
console.log("ADMINISTRATOR_NAME: "+ADMINISTRATOR_NAME);
console.log("ADMINISTRATOR_EMAIL: "+ADMINISTRATOR_EMAIL);
console.log("ADMINISTRATOR_CREATEDON: "+ADMINISTRATOR_CREATEDON);
console.log("ADMINISTRATOR_COUNTRY: "+ADMINISTRATOR_COUNTRY);
console.log("ADMINISTRATOR_CURRENCY: "+ADMINISTRATOR_CURRENCY);
console.log("ADMINISTRATOR_TIMEZONE: "+ADMINISTRATOR_TIMEZONE);
/* LIVE SUPPORT ACCOUNT */
var HWG_LIVESUPPORT_ACCOUNTID='<?php if(isset($_SESSION["HWG_LIVESUPPORT_ACCOUNTID"])){ echo $_SESSION["HWG_LIVESUPPORT_ACCOUNTID"]; } ?>';
var HWG_LIVESUPPORT_AVAILSTATUS='<?php if(isset($_SESSION["HWG_LIVESUPPORT_AVAILSTATUS"])){ echo $_SESSION["HWG_LIVESUPPORT_AVAILSTATUS"]; } ?>';
var HWG_LIVESUPPORT_NAME='<?php if(isset($_SESSION["HWG_LIVESUPPORT_NAME"])){ echo $_SESSION["HWG_LIVESUPPORT_NAME"]; } ?>';
var HWG_LIVESUPPORT_CREATEDON='<?php if(isset($_SESSION["HWG_LIVESUPPORT_CREATEDON"])){ echo $_SESSION["HWG_LIVESUPPORT_CREATEDON"]; } ?>';
var HWG_LIVESUPPORT_COUNTRY='<?php if(isset($_SESSION["HWG_LIVESUPPORT_COUNTRY"])){ echo $_SESSION["HWG_LIVESUPPORT_COUNTRY"]; } ?>';
var HWG_LIVESUPPORT_SHIFT='<?php if(isset($_SESSION["HWG_LIVESUPPORT_SHIFT"])){ echo $_SESSION["HWG_LIVESUPPORT_SHIFT"]; } ?>';
var HWG_LIVESUPPORT_USRTIMEZONE='<?php if(isset($_SESSION["HWG_LIVESUPPORT_USRTIMEZONE"])){ echo $_SESSION["HWG_LIVESUPPORT_USRTIMEZONE"]; } ?>';
var HWG_LIVESUPPORT_STARTTIME='<?php if(isset($_SESSION["HWG_LIVESUPPORT_STARTTIME"])){ echo $_SESSION["HWG_LIVESUPPORT_STARTTIME"]; } ?>';
var HWG_LIVESUPPORT_ENDTIME='<?php if(isset($_SESSION["HWG_LIVESUPPORT_ENDTIME"])){ echo $_SESSION["HWG_LIVESUPPORT_ENDTIME"]; } ?>';
console.log("HWG_LIVESUPPORT_ACCOUNTID: "+HWG_LIVESUPPORT_ACCOUNTID);
console.log("HWG_LIVESUPPORT_AVAILSTATUS: "+HWG_LIVESUPPORT_AVAILSTATUS);
console.log("HWG_LIVESUPPORT_NAME: "+HWG_LIVESUPPORT_NAME);
console.log("HWG_LIVESUPPORT_CREATEDON: "+HWG_LIVESUPPORT_CREATEDON);
console.log("HWG_LIVESUPPORT_COUNTRY: "+HWG_LIVESUPPORT_COUNTRY);
console.log("HWG_LIVESUPPORT_SHIFT: "+HWG_LIVESUPPORT_SHIFT);
console.log("HWG_LIVESUPPORT_USRTIMEZONE: "+HWG_LIVESUPPORT_USRTIMEZONE);
console.log("HWG_LIVESUPPORT_STARTTIME: "+HWG_LIVESUPPORT_STARTTIME);
console.log("HWG_LIVESUPPORT_ENDTIME: "+HWG_LIVESUPPORT_ENDTIME);
/* ACCOUNT_HOLDERS */
var ACCOUNT_ID = '<?php if(isset($_SESSION["HWG_ACCOUNT_ID"])) { echo $_SESSION["HWG_ACCOUNT_ID"]; } ?>';
var ACCOUNT_AVAILSTATUS = '<?php if(isset($_SESSION["HWG_ACCOUNT_AVAILSTATUS"])) { echo $_SESSION["HWG_ACCOUNT_AVAILSTATUS"]; } ?>';
var ACCOUNT_NAME = '<?php if(isset($_SESSION["HWG_ACCOUNT_NAME"])) { echo $_SESSION["HWG_ACCOUNT_NAME"]; } ?>';
var ACCOUNT_EMAIL = '<?php if(isset($_SESSION["HWG_ACCOUNT_EMAIL"])) { echo $_SESSION["HWG_ACCOUNT_EMAIL"]; } ?>';
var ACCOUNT_CREATED = '<?php if(isset($_SESSION["HWG_ACCOUNT_CREATED"])) { echo $_SESSION["HWG_ACCOUNT_CREATED"]; } ?>';
var ACCOUNT_COUNTRY = '<?php if(isset($_SESSION["HWG_ACCOUNT_COUNTRY"])) { echo $_SESSION["HWG_ACCOUNT_COUNTRY"]; } ?>';
var ACCOUNT_PASSWORD = '<?php if(isset($_SESSION["HWG_ACCOUNT_PASSWORD"])) { echo $_SESSION["HWG_ACCOUNT_PASSWORD"]; } ?>';
console.log("PROJECT_URL: "+PROJECT_URL);
console.log("USR_LANG: "+USR_LANG);
console.log("SESSION_ID: "+SESSION_ID);
console.log("CLIENT_IPADDRESS: "+CLIENT_IPADDRESS);
console.log("QUEUE_ADDEDON: "+QUEUE_ADDEDON);


console.log("ACCOUNT_ID: "+ACCOUNT_ID);
console.log("ACCOUNT_AVAILSTATUS: "+ACCOUNT_AVAILSTATUS);
console.log("ACCOUNT_NAME: "+ACCOUNT_NAME);
console.log("ACCOUNT_EMAIL: "+ACCOUNT_EMAIL);
console.log("ACCOUNT_CREATED: "+ACCOUNT_CREATED);
console.log("ACCOUNT_COUNTRY: "+ACCOUNT_COUNTRY);
</script>